baseurl = "/"
languageCode = "ja-jp"
title = "capyBaral"
publishDir = "docs"
theme = "hugo-classic"
disqusShortname = ""
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
enableEmoji = true
footnotereturnlinkcontents = "↩"
hasCJKLanguage = true

[permalinks]
    post = "/post/:year/:month/:day/:filename/"
    doc = "/doc/:filename/"
[author]
    name = "B-SAKATU"
    email = "bsakatu.bleu.blanc.rouge@gmail.com"
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
[[menu.feed]]
    name = "Subscribe"
    url = "/index.xml"

[params]
    brand = "bsakatu.net"
    description = ""
    copyrighthtml = "Copyright &copy; 2020 B-SAKATU"
    footer = ""
    custom_css = ["css/theme-override.css"]
    twitter = "bsakatu"
    github = "bsakatu"
    hatena = "B-SAKATU"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xhtml = false
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    style = "manni"
    tabWidth = 4