baseurl = "/"
languageCode = "ja-jp"
title = "capyBaral"
publishDir = "docs"
disqusShortname = ""
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
enableEmoji = true
footnotereturnlinkcontents = "↩"
hasCJKLanguage = true

[permalinks]
    post = "/post/:year/:month/:day/:filename/"
    doc = "/:sections/:filename/"
    top = "/:"
[author]
    name = "B-SAKATU"
    email = ""
[[menu.main]]
    name = "Zatsu"
    url = "/post/"
    weight = 1
[[menu.main]]
    name = "Doc"
    url = "/doc/"
    weight = 2
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4
[[menu.feed]]
    name = "Feed"
    url = "/index.xml"

[params]
    brand = "bsakatu.net"
    author = "B-SAKATU"
    description = ""
    firstpostdate = 2018-11-01
    copyrighthtml = "&copy;"
    footer = ""
    custom_css = ["css/theme-override.css"]
    twitter = "bsakatu"
    github = "bsakatu"
    hatena = "B-SAKATU"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = false
      strikethrough = true
      table = true
      taskList = true
      typographer = false
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    style = "manni"
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 3
    ordered = true
    startLevel = 2
